# Generated by Django 5.0.6 on 2024-08-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porn_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actors',
            old_name='name',
            new_name='title',
        ),
    ]
