# Generated by Django 5.0.6 on 2024-08-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porn_site', '0002_rename_name_actors_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='photo',
            field=models.ImageField(upload_to='actor_photo'),
        ),
        migrations.AlterField(
            model_name='films',
            name='actor',
            field=models.ManyToManyField(related_name='films', to='porn_site.actors'),
        ),
        migrations.AlterField(
            model_name='films',
            name='preview',
            field=models.ImageField(upload_to='film_preview'),
        ),
        migrations.AlterField(
            model_name='films',
            name='studio',
            field=models.ManyToManyField(related_name='studio', to='porn_site.studio'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='photo',
            field=models.ImageField(upload_to='studio_photo'),
        ),
    ]
