# Generated by Django 5.0.6 on 2024-08-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porn_site', '0003_alter_actors_photo_alter_films_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
