# Generated by Django 5.0.6 on 2024-08-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porn_site', '0004_actors_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='studio',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='URL'),
        ),
    ]
