# Generated by Django 5.0.6 on 2024-08-12 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porn_site', '0005_films_slug_studio_slug_alter_actors_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='favourite_video',
            field=models.ManyToManyField(related_name='favourite_video', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actors',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Национальность'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='photo',
            field=models.ImageField(upload_to='actor_photo', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
