# Generated by Django 5.0.6 on 2024-08-12 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porn_site', '0006_films_favourite_video_alter_actors_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='favourite_video',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite_video', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='films',
            name='studio',
        ),
        migrations.AddField(
            model_name='films',
            name='studio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='studio', to='porn_site.studio'),
        ),
    ]
