# Generated by Django 5.0.6 on 2024-08-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porn_site', '0007_alter_films_favourite_video_remove_films_studio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='studio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='studio', to='porn_site.studio'),
        ),
    ]
