# Generated by Django 5.0.6 on 2024-08-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porn_site', '0009_alter_films_studio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='films',
            name='studio',
        ),
        migrations.AddField(
            model_name='films',
            name='studio',
            field=models.ManyToManyField(related_name='studio', to='porn_site.studio'),
        ),
    ]
